<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE note[
        <!ELEMENT note (to,from,heading,body)>
        <!ELEMENT to         (#PCDATA)>
        <!ELEMENT from       (#PCDATA)>
        <!ELEMENT heading    (#PCDATA)>
        <!ELEMENT body       (#PCDATA)>
        ]>
<note>
    <to>Deorge</to>
    <from>John</from>
    <heading>Reminder</heading>
    <body>Don't forget te meeting!</body>
</note>
